/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package login;


import customGUI.MyMessage;
import customGUI.MyPasswordField;
import customGUI.MyTextField;


import java.awt.event.KeyEvent;






import sqlite.adminSqlite;
import sqlite.loginAccount;




/**
 *
 * @author Admin
 */
public class login extends javax.swing.JDialog {
    
 
    public login(){
        
    }
    
    public login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        
        showpassword.setVisible(false);
        signupshowpassword.setVisible(false);
       showconfirmpassword.setVisible(false);
        txtpassword.setEchoChar((char)0);
        txtpassword1.setEchoChar((char)0);
        txtconfirmpassword.setEchoChar((char)0);
        lblvalid1.setVisible(false);
        lblvalid2.setVisible(false);
        lblvalid3.setVisible(false);
        datePicker2.getComponentDateTextField().setEnabled(false);
        
        new adminSqlite().addValueCourseCB(cbcourse);
        new adminSqlite().addValueYearCB(cbyear);
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        showpassword = new javax.swing.JCheckBox();
        btnsignin = new customGUI.MyButton();
        txtpassword = new customGUI.MyPasswordField();
        txtusername = new customGUI.MyTextField();
        jPanel3 = new javax.swing.JPanel();
        signupshowpassword = new javax.swing.JCheckBox();
        showconfirmpassword = new javax.swing.JCheckBox();
        txtpassword1 = new customGUI.MyPasswordField();
        txtusername1 = new customGUI.MyTextField();
        txtidnum = new customGUI.MyTextField();
        txtfirstname = new customGUI.MyTextField();
        txtlastname = new customGUI.MyTextField();
        cbcourse = new javax.swing.JComboBox<>();
        cbyear = new javax.swing.JComboBox<>();
        cbgender = new javax.swing.JComboBox<>();
        txtconfirmpassword = new customGUI.MyPasswordField();
        btnsignin1 = new customGUI.MyButton();
        datePicker2 = new com.github.lgooddatepicker.components.DatePicker();
        lblvalid2 = new javax.swing.JLabel();
        lblvalid1 = new javax.swing.JLabel();
        lblvalid3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        signuppanel = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        btnsignup = new customGUI.MyButton();
        labelwelcome2 = new javax.swing.JLabel();
        labelwelcome1 = new javax.swing.JLabel();
        labelwelcome = new javax.swing.JLabel();
        btnsignin3 = new customGUI.MyButton();
        myPicture2 = new customGUI.myPicture("ATTENDANCE.png");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusable(false);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        showpassword.setContentAreaFilled(false);
        showpassword.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\image\\9041325_eye_fill_icon (3).png"));
        showpassword.setSelectedIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\image\\9034884_eye_off_icon (1).png"));
        showpassword.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                showpasswordStateChanged(evt);
            }
        });
        showpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(showpassword);
        showpassword.setBounds(260, 300, 19, 20);

        btnsignin.setText("Sign In");
        btnsignin.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnsignin.setForeground(new java.awt.Color(255, 255, 255));
        btnsignin.setRadius(50);
        btnsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsigninActionPerformed(evt);
            }
        });
        jPanel2.add(btnsignin);
        btnsignin.setBounds(40, 370, 246, 42);

        txtpassword.setText("Password");
        txtpassword.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\image\\8491307_padlock_security_password_icon.png"));
        txtpassword.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                txtpasswordHierarchyChanged(evt);
            }
        });
        txtpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpasswordFocusLost(evt);
            }
        });
        txtpassword.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtpasswordInputMethodTextChanged(evt);
            }
        });
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        txtpassword.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtpasswordPropertyChange(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpasswordKeyTyped(evt);
            }
        });
        jPanel2.add(txtpassword);
        txtpassword.setBounds(40, 290, 250, 50);

        txtusername.setBackground(new java.awt.Color(0, 0, 0,0));
        txtusername.setText("Username");
        txtusername.setBorderColor(new java.awt.Color(230, 245, 241));
        txtusername.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\image\\11185794_user_person_profile_avatar_people_icon (1).png"));
        txtusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameFocusLost(evt);
            }
        });
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtusernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusernameKeyTyped(evt);
            }
        });
        jPanel2.add(txtusername);
        txtusername.setBounds(40, 210, 250, 50);

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        signupshowpassword.setContentAreaFilled(false);
        signupshowpassword.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\image\\9041325_eye_fill_icon (3).png"));
        signupshowpassword.setSelectedIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\image\\9034884_eye_off_icon (1).png"));
        signupshowpassword.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                signupshowpasswordStateChanged(evt);
            }
        });
        signupshowpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupshowpasswordActionPerformed(evt);
            }
        });
        jPanel3.add(signupshowpassword);
        signupshowpassword.setBounds(280, 460, 19, 20);

        showconfirmpassword.setContentAreaFilled(false);
        showconfirmpassword.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\image\\9041325_eye_fill_icon (3).png"));
        showconfirmpassword.setSelectedIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\image\\9034884_eye_off_icon (1).png"));
        showconfirmpassword.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                showconfirmpasswordStateChanged(evt);
            }
        });
        showconfirmpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showconfirmpasswordActionPerformed(evt);
            }
        });
        jPanel3.add(showconfirmpassword);
        showconfirmpassword.setBounds(280, 530, 19, 20);

        txtpassword1.setText("Password");
        txtpassword1.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\image\\8491307_padlock_security_password_icon.png"));
        txtpassword1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                txtpassword1HierarchyChanged(evt);
            }
        });
        txtpassword1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpassword1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpassword1FocusLost(evt);
            }
        });
        txtpassword1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtpassword1InputMethodTextChanged(evt);
            }
        });
        txtpassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassword1ActionPerformed(evt);
            }
        });
        txtpassword1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtpassword1PropertyChange(evt);
            }
        });
        txtpassword1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpassword1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpassword1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpassword1KeyTyped(evt);
            }
        });
        jPanel3.add(txtpassword1);
        txtpassword1.setBounds(30, 450, 280, 40);

        txtusername1.setBackground(new java.awt.Color(0, 0, 0,0));
        txtusername1.setText("Username");
        txtusername1.setBorderColor(new java.awt.Color(230, 245, 241));
        txtusername1.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\image\\11185794_user_person_profile_avatar_people_icon (1).png"));
        txtusername1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusername1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusername1FocusLost(evt);
            }
        });
        txtusername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusername1ActionPerformed(evt);
            }
        });
        txtusername1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtusername1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusername1KeyTyped(evt);
            }
        });
        jPanel3.add(txtusername1);
        txtusername1.setBounds(30, 370, 280, 40);

        txtidnum.setBackground(new java.awt.Color(0, 0, 0,0));
        txtidnum.setText("Id Number");
        txtidnum.setBorderColor(new java.awt.Color(230, 245, 241));
        txtidnum.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\StudentAttend\\11185794_user_person_profile_avatar_people_icon (1).png"));
        txtidnum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtidnumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtidnumFocusLost(evt);
            }
        });
        txtidnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidnumActionPerformed(evt);
            }
        });
        txtidnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidnumKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidnumKeyTyped(evt);
            }
        });
        jPanel3.add(txtidnum);
        txtidnum.setBounds(30, 140, 280, 40);

        txtfirstname.setBackground(new java.awt.Color(0, 0, 0,0));
        txtfirstname.setText("First Name");
        txtfirstname.setBorderColor(new java.awt.Color(230, 245, 241));
        txtfirstname.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\StudentAttend\\11185794_user_person_profile_avatar_people_icon (1).png"));
        txtfirstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfirstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfirstnameFocusLost(evt);
            }
        });
        txtfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirstnameActionPerformed(evt);
            }
        });
        txtfirstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfirstnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfirstnameKeyTyped(evt);
            }
        });
        jPanel3.add(txtfirstname);
        txtfirstname.setBounds(30, 200, 130, 40);

        txtlastname.setBackground(new java.awt.Color(0, 0, 0,0));
        txtlastname.setText("Last Name");
        txtlastname.setBorderColor(new java.awt.Color(230, 245, 241));
        txtlastname.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\StudentAttend\\11185794_user_person_profile_avatar_people_icon (1).png"));
        txtlastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtlastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtlastnameFocusLost(evt);
            }
        });
        txtlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlastnameActionPerformed(evt);
            }
        });
        txtlastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlastnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlastnameKeyTyped(evt);
            }
        });
        jPanel3.add(txtlastname);
        txtlastname.setBounds(180, 200, 130, 40);

        cbcourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course" }));
        cbcourse.setBackground(new java.awt.Color(0,0,0,0));
        cbcourse.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbcourse.setForeground(new java.awt.Color(122, 140, 141));
        jPanel3.add(cbcourse);
        cbcourse.setBounds(30, 320, 140, 40);

        cbyear.setBackground(new java.awt.Color(0,0,0,0));
        cbyear.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbyear.setForeground(new java.awt.Color(122, 140, 141));
        cbyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Year" }));
        jPanel3.add(cbyear);
        cbyear.setBounds(190, 320, 120, 40);

        cbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female", "Others" }));
        cbgender.setBackground(new java.awt.Color(0,0,0,0));
        cbgender.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        cbgender.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbgender.setForeground(new java.awt.Color(122, 140, 141));
        cbgender.setRequestFocusEnabled(false);
        jPanel3.add(cbgender);
        cbgender.setBounds(30, 260, 120, 40);

        txtconfirmpassword.setText("Confirm Password");
        txtconfirmpassword.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\image\\8491307_padlock_security_password_icon.png"));
        txtconfirmpassword.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                txtconfirmpasswordHierarchyChanged(evt);
            }
        });
        txtconfirmpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtconfirmpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtconfirmpasswordFocusLost(evt);
            }
        });
        txtconfirmpassword.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtconfirmpasswordInputMethodTextChanged(evt);
            }
        });
        txtconfirmpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconfirmpasswordActionPerformed(evt);
            }
        });
        txtconfirmpassword.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtconfirmpasswordPropertyChange(evt);
            }
        });
        txtconfirmpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtconfirmpasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtconfirmpasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtconfirmpasswordKeyTyped(evt);
            }
        });
        jPanel3.add(txtconfirmpassword);
        txtconfirmpassword.setBounds(30, 520, 280, 40);

        btnsignin1.setText("Sign Up");
        btnsignin1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnsignin1.setForeground(new java.awt.Color(255, 255, 255));
        btnsignin1.setRadius(50);
        btnsignin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignin1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnsignin1);
        btnsignin1.setBounds(50, 580, 246, 42);
        jPanel3.add(datePicker2);
        datePicker2.setBounds(150, 260, 160, 40);

        lblvalid2.setText("The Confirm Password  didnt Match up! ");
        lblvalid2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(lblvalid2);
        lblvalid2.setBounds(30, 560, 300, 16);

        lblvalid1.setText("The Confirm Password didnt Match up!");
        lblvalid1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(lblvalid1);
        lblvalid1.setBounds(30, 490, 240, 16);

        lblvalid3.setForeground(new java.awt.Color(255, 0, 0));
        lblvalid3.setText("Username is Already Have Taken Please Input Another");
        jPanel3.add(lblvalid3);
        lblvalid3.setBounds(30, 410, 290, 16);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("BOD(Date Of Birth)");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(150, 250, 150, 10);

        jTabbedPane1.addTab("tab2", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 330, 680));

        signuppanel.setBackground(new java.awt.Color(39, 159, 217));
        signuppanel.setForeground(new java.awt.Color(30, 30, 30));
        signuppanel.setLayout(null);

        label1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Still Havent Join Us?");
        signuppanel.add(label1);
        label1.setBounds(190, 520, 250, 19);

        btnsignup.setText("Sign Up");
        btnsignup.setBorderColor(new java.awt.Color(0, 0, 0));
        btnsignup.setColor(new java.awt.Color(0, 0, 0));
        btnsignup.setColorClick(new java.awt.Color(102, 102, 102));
        btnsignup.setColorOver(new java.awt.Color(51, 51, 51));
        btnsignup.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnsignup.setForeground(new java.awt.Color(255, 255, 255));
        btnsignup.setRadius(50);
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        signuppanel.add(btnsignup);
        btnsignup.setBounds(130, 540, 268, 40);

        labelwelcome2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        labelwelcome2.setForeground(new java.awt.Color(255, 255, 255));
        labelwelcome2.setText("System");
        signuppanel.add(labelwelcome2);
        labelwelcome2.setBounds(220, 120, 90, 32);

        labelwelcome1.setFont(new java.awt.Font("SansSerif", 1, 42)); // NOI18N
        labelwelcome1.setForeground(new java.awt.Color(255, 255, 255));
        labelwelcome1.setText("Event Attendance ");
        signuppanel.add(labelwelcome1);
        labelwelcome1.setBounds(80, 80, 370, 54);

        labelwelcome.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        labelwelcome.setForeground(new java.awt.Color(255, 255, 255));
        labelwelcome.setText("Welcome User");
        signuppanel.add(labelwelcome);
        labelwelcome.setBounds(140, 20, 250, 47);

        btnsignin3.setForeground(new java.awt.Color(255, 255, 255));
        btnsignin3.setText("Sign In");
        btnsignin3.setBorderColor(new java.awt.Color(0, 0, 0));
        btnsignin3.setColor(new java.awt.Color(0, 0, 0));
        btnsignin3.setColorClick(new java.awt.Color(102, 102, 102));
        btnsignin3.setColorOver(new java.awt.Color(51, 51, 51));
        btnsignin3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnsignin3.setRadius(50);
        btnsignin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignin3ActionPerformed(evt);
            }
        });
        signuppanel.add(btnsignin3);
        btnsignin3.setBounds(130, 540, 268, 40);

        myPicture2.setBackground(new java.awt.Color(0, 0, 0,0));
        signuppanel.add(myPicture2);
        myPicture2.setBounds(-10, 110, 510, 460);

        getContentPane().add(signuppanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, -1, 480, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showpasswordStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_showpasswordStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_showpasswordStateChanged

    private void showpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordActionPerformed
      new MyPasswordField().showpasswordChar(showpassword, txtpassword);
    }//GEN-LAST:event_showpasswordActionPerformed

    private void btnsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsigninActionPerformed
       
    
    new loginAccount(this,txtusername.getText(),txtpassword.getText());
  
    }//GEN-LAST:event_btnsigninActionPerformed

    private void txtpasswordHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_txtpasswordHierarchyChanged

    }//GEN-LAST:event_txtpasswordHierarchyChanged

    private void txtpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusGained
      new MyPasswordField().focusGained(txtpassword, "Password", showpassword);
    }//GEN-LAST:event_txtpasswordFocusGained

    private void txtpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusLost
       new MyPasswordField().focusLost(txtpassword, "Password", showpassword);
    }//GEN-LAST:event_txtpasswordFocusLost

    private void txtpasswordInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtpasswordInputMethodTextChanged

    }//GEN-LAST:event_txtpasswordInputMethodTextChanged

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed

    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtpasswordPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtpasswordPropertyChange

    }//GEN-LAST:event_txtpasswordPropertyChange

    private void txtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyPressed
      new MyPasswordField().checkEmpty(txtpassword, showpassword, "Password");
    }//GEN-LAST:event_txtpasswordKeyPressed

    private void txtpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyReleased

    }//GEN-LAST:event_txtpasswordKeyReleased

    private void txtpasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyTyped

    }//GEN-LAST:event_txtpasswordKeyTyped

    private void txtusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusGained
        new MyTextField().focuseGained(txtusername, "Username");
    }//GEN-LAST:event_txtusernameFocusGained

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusLost
       new  MyTextField().focusLost(txtusername, "Username");
    }//GEN-LAST:event_txtusernameFocusLost

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void txtusernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameKeyReleased

    private void txtusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameKeyTyped

    private void signupshowpasswordStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_signupshowpasswordStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_signupshowpasswordStateChanged

    private void signupshowpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupshowpasswordActionPerformed
      new MyPasswordField().showpasswordChar(signupshowpassword,txtpassword1);
    }//GEN-LAST:event_signupshowpasswordActionPerformed

    private void showconfirmpasswordStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_showconfirmpasswordStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_showconfirmpasswordStateChanged

    private void showconfirmpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showconfirmpasswordActionPerformed
       new MyPasswordField().showpasswordChar(showconfirmpassword,txtconfirmpassword);
    }//GEN-LAST:event_showconfirmpasswordActionPerformed

    private void txtpassword1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_txtpassword1HierarchyChanged

    }//GEN-LAST:event_txtpassword1HierarchyChanged

    private void txtpassword1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassword1FocusGained
       new MyPasswordField().focusGained(txtpassword1, "Password", signupshowpassword);
    }//GEN-LAST:event_txtpassword1FocusGained

    private void txtpassword1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassword1FocusLost
      new MyPasswordField().focusLost(txtpassword1, "Password", signupshowpassword);
    }//GEN-LAST:event_txtpassword1FocusLost

    private void txtpassword1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtpassword1InputMethodTextChanged

    }//GEN-LAST:event_txtpassword1InputMethodTextChanged

    private void txtpassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassword1ActionPerformed
       new MyPasswordField().checkvalidation(lblvalid1,lblvalid2, txtpassword1,txtconfirmpassword);
       if(new MyPasswordField().isValidation() == false){
           new MyMessage(null,false).message("REMINDER","The confirm password and pass didnt match please match the two to procceed", "INFORMATION", "OK","OK");
             jTabbedPane1.setSelectedIndex(1);
           
           return;
       }
        jTabbedPane1.setSelectedIndex(0);
        btnsignin3.setVisible(false);
        btnsignup.setVisible(true);
             
    }//GEN-LAST:event_txtpassword1ActionPerformed

    private void txtpassword1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtpassword1PropertyChange
       
    }//GEN-LAST:event_txtpassword1PropertyChange

    private void txtpassword1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassword1KeyPressed
    new MyPasswordField().checkEmpty(txtpassword1, signupshowpassword, "Username");
    }//GEN-LAST:event_txtpassword1KeyPressed

    private void txtpassword1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassword1KeyReleased

    }//GEN-LAST:event_txtpassword1KeyReleased

    private void txtpassword1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassword1KeyTyped

    }//GEN-LAST:event_txtpassword1KeyTyped

    private void txtusername1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusername1FocusGained
         new MyTextField().focuseGained(txtusername1, "Username");
        
    }//GEN-LAST:event_txtusername1FocusGained

    private void txtusername1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusername1FocusLost
     new MyTextField().focusLost(txtusername1, "Username");
    }//GEN-LAST:event_txtusername1FocusLost

    private void txtusername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusername1ActionPerformed

    private void txtusername1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusername1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusername1KeyReleased

    private void txtusername1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusername1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusername1KeyTyped

    private void txtidnumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidnumFocusGained
        new MyTextField().focuseGained(txtidnum, "Id Number");
    }//GEN-LAST:event_txtidnumFocusGained

    private void txtidnumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidnumFocusLost
        new MyTextField().focusLost(txtidnum, "Id Number");
    }//GEN-LAST:event_txtidnumFocusLost

    private void txtidnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidnumActionPerformed

    private void txtidnumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidnumKeyReleased
        if(txtidnum.getText().isEmpty()){
            txtidnum.setCustomIcon2(null);
        }else{

            txtidnum.setCustomIcon2(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\image\\22 (2).gif"));

        }
    }//GEN-LAST:event_txtidnumKeyReleased

    private void txtidnumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidnumKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c== KeyEvent.VK_DELETE)) {
            evt.consume();
   
           new MyMessage(null,true).message("NOTIFICATION", "This textbox is only ID you can enter please Enter A Number", "INFORMATION MESSAGE","Ok","Close");
           
            txtidnum.setCustomIcon2(null);
        }else {
           
            txtidnum.setCustomIcon2(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\image\\22 (2).gif"));

        }
    }//GEN-LAST:event_txtidnumKeyTyped

    private void txtfirstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfirstnameFocusGained
       new MyTextField().focuseGained(txtfirstname,"First Name");
    }//GEN-LAST:event_txtfirstnameFocusGained

    private void txtfirstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfirstnameFocusLost
        new MyTextField().focusLost(txtfirstname, "First Name");
    }//GEN-LAST:event_txtfirstnameFocusLost

    private void txtfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstnameActionPerformed

    private void txtfirstnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfirstnameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstnameKeyReleased

    private void txtfirstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfirstnameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstnameKeyTyped

    private void txtlastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlastnameFocusGained
        new MyTextField().focuseGained(txtlastname, "Last Name");
    }//GEN-LAST:event_txtlastnameFocusGained

    private void txtlastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlastnameFocusLost
        new MyTextField().focuseGained(txtlastname,"Last Name");
    }//GEN-LAST:event_txtlastnameFocusLost

    private void txtlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameActionPerformed

    private void txtlastnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlastnameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameKeyReleased

    private void txtlastnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlastnameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameKeyTyped

    private void txtconfirmpasswordHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_txtconfirmpasswordHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmpasswordHierarchyChanged

    private void txtconfirmpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtconfirmpasswordFocusGained
        new MyPasswordField().focusGained(txtconfirmpassword, "Confirm Password", showconfirmpassword);
    }//GEN-LAST:event_txtconfirmpasswordFocusGained

    private void txtconfirmpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtconfirmpasswordFocusLost
       new MyPasswordField().focusLost(txtconfirmpassword, "Confirm Password", showconfirmpassword);
    }//GEN-LAST:event_txtconfirmpasswordFocusLost

    private void txtconfirmpasswordInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtconfirmpasswordInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmpasswordInputMethodTextChanged

    private void txtconfirmpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconfirmpasswordActionPerformed
   new MyPasswordField().checkvalidation(lblvalid1,lblvalid2, txtpassword1,txtconfirmpassword);
       if(new MyPasswordField().isValidation() == false){
             jTabbedPane1.setSelectedIndex(1);
             
             new MyMessage(null,false).message("REMINDER", "The Confirm Password and Password Didnt Match! ","INFORMATION", "OK", "OK");
           return;
       }
         jTabbedPane1.setSelectedIndex(0);
         btnsignin3.setVisible(false);
         btnsignup.setVisible(true);    
    }//GEN-LAST:event_txtconfirmpasswordActionPerformed

    private void txtconfirmpasswordPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtconfirmpasswordPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmpasswordPropertyChange

    private void txtconfirmpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconfirmpasswordKeyPressed
        new MyPasswordField().checkEmpty(txtconfirmpassword, showconfirmpassword, "Confirm Password");
    }//GEN-LAST:event_txtconfirmpasswordKeyPressed

    private void txtconfirmpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconfirmpasswordKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmpasswordKeyReleased

    private void txtconfirmpasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconfirmpasswordKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmpasswordKeyTyped

    private void btnsignin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignin1ActionPerformed
       new MyPasswordField().checkvalidation(lblvalid1,lblvalid2, txtpassword1,txtconfirmpassword);
       if(new MyPasswordField().isValidation() == false){
           new MyMessage(null,false).message("REMINDER","The Confirm Password and Password Dint Match Please Check","INFORMATION","OK", "OK");
           return;
       }
       
       
      new MyMessage(null,true).message("SUCCESSFULLY", "The Account Successfully Created Is now waiting to accepted by Admin ", "INFORMATION", "THANKS", "THANKS");
       jTabbedPane1.setSelectedIndex(0);
       btnsignin3.setVisible(false);
       btnsignup.setVisible(true);
    }//GEN-LAST:event_btnsignin1ActionPerformed

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
              jTabbedPane1.setSelectedIndex(1);
              btnsignup.setVisible(false);
              btnsignin3.setVisible(true);
             label1.setText("Already have Account?");
    }//GEN-LAST:event_btnsignupActionPerformed

    private void btnsignin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignin3ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        btnsignin3.setVisible(false);
        btnsignup.setVisible(true);
        label1.setText("Still Havent Join Us");
        
    }//GEN-LAST:event_btnsignin3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                login dialog = new login(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customGUI.MyButton btnsignin;
    private customGUI.MyButton btnsignin1;
    private customGUI.MyButton btnsignin3;
    private customGUI.MyButton btnsignup;
    private javax.swing.JComboBox<String> cbcourse;
    private javax.swing.JComboBox<String> cbgender;
    private javax.swing.JComboBox<String> cbyear;
    private com.github.lgooddatepicker.components.DatePicker datePicker2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel labelwelcome;
    private javax.swing.JLabel labelwelcome1;
    private javax.swing.JLabel labelwelcome2;
    private javax.swing.JLabel lblvalid1;
    private javax.swing.JLabel lblvalid2;
    private javax.swing.JLabel lblvalid3;
    private customGUI.myPicture myPicture2;
    private javax.swing.JCheckBox showconfirmpassword;
    private javax.swing.JCheckBox showpassword;
    private javax.swing.JPanel signuppanel;
    private javax.swing.JCheckBox signupshowpassword;
    private customGUI.MyPasswordField txtconfirmpassword;
    private customGUI.MyTextField txtfirstname;
    private customGUI.MyTextField txtidnum;
    private customGUI.MyTextField txtlastname;
    private customGUI.MyPasswordField txtpassword;
    private customGUI.MyPasswordField txtpassword1;
    private customGUI.MyTextField txtusername;
    private customGUI.MyTextField txtusername1;
    // End of variables declaration//GEN-END:variables
}
