/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.awt.event.KeyEvent;
import login.signin;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class signup extends javax.swing.JFrame {

   
    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
          txtpassword.setEchoChar((char)0);
         showpassword.setVisible(false);
         txtconfirmpassword.setEchoChar((char)0);
         showconfirmpassword.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signuppanel = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        btnsignup = new customGUI.MyButton();
        labelwelcome = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        showpassword = new javax.swing.JCheckBox();
        showconfirmpassword = new javax.swing.JCheckBox();
        txtpassword = new customGUI.MyPasswordField();
        txtusername = new customGUI.MyTextField();
        txtfirstname = new customGUI.MyTextField();
        txtfirstname1 = new customGUI.MyTextField();
        txtlastname = new customGUI.MyTextField();
        cbcourse = new javax.swing.JComboBox<>();
        cbyear = new javax.swing.JComboBox<>();
        cbgender = new javax.swing.JComboBox<>();
        txtconfirmpassword = new customGUI.MyPasswordField();
        btnsignin = new customGUI.MyButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        signuppanel.setBackground(new java.awt.Color(39, 159, 217));
        signuppanel.setForeground(new java.awt.Color(30, 30, 30));

        label1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Already Have an Account?");

        btnsignup.setForeground(new java.awt.Color(255, 255, 255));
        btnsignup.setText("Sign In");
        btnsignup.setBorderColor(new java.awt.Color(0, 0, 0));
        btnsignup.setColor(new java.awt.Color(0, 0, 0));
        btnsignup.setColorClick(new java.awt.Color(102, 102, 102));
        btnsignup.setColorOver(new java.awt.Color(51, 51, 51));
        btnsignup.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnsignup.setRadius(50);
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });

        labelwelcome.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        labelwelcome.setForeground(new java.awt.Color(255, 255, 255));
        labelwelcome.setText("Join Us User");

        javax.swing.GroupLayout signuppanelLayout = new javax.swing.GroupLayout(signuppanel);
        signuppanel.setLayout(signuppanelLayout);
        signuppanelLayout.setHorizontalGroup(
            signuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signuppanelLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(signuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signuppanelLayout.createSequentialGroup()
                        .addComponent(btnsignup, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signuppanelLayout.createSequentialGroup()
                        .addComponent(labelwelcome)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signuppanelLayout.createSequentialGroup()
                        .addComponent(label1)
                        .addGap(118, 118, 118))))
        );
        signuppanelLayout.setVerticalGroup(
            signuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signuppanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(labelwelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsignup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        showpassword.setContentAreaFilled(false);
        showpassword.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\image\\9041325_eye_fill_icon (3).png"));
        showpassword.setSelectedIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\image\\9034884_eye_off_icon (1).png"));
        showpassword.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                showpasswordStateChanged(evt);
            }
        });
        showpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(showpassword);
        showpassword.setBounds(280, 350, 19, 20);

        showconfirmpassword.setContentAreaFilled(false);
        showconfirmpassword.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\image\\9041325_eye_fill_icon (3).png"));
        showconfirmpassword.setSelectedIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\image\\9034884_eye_off_icon (1).png"));
        showconfirmpassword.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                showconfirmpasswordStateChanged(evt);
            }
        });
        showconfirmpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showconfirmpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(showconfirmpassword);
        showconfirmpassword.setBounds(280, 410, 19, 20);

        txtpassword.setText("Password");
        txtpassword.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\StudentAttend\\8491307_padlock_security_password_icon.png"));
        txtpassword.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                txtpasswordHierarchyChanged(evt);
            }
        });
        txtpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpasswordFocusLost(evt);
            }
        });
        txtpassword.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtpasswordInputMethodTextChanged(evt);
            }
        });
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        txtpassword.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtpasswordPropertyChange(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpasswordKeyTyped(evt);
            }
        });
        jPanel2.add(txtpassword);
        txtpassword.setBounds(30, 340, 280, 40);

        txtusername.setBackground(new java.awt.Color(0, 0, 0,0));
        txtusername.setText("Username");
        txtusername.setBorderColor(new java.awt.Color(230, 245, 241));
        txtusername.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\StudentAttend\\11185794_user_person_profile_avatar_people_icon (1).png"));
        txtusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameFocusLost(evt);
            }
        });
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtusernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusernameKeyTyped(evt);
            }
        });
        jPanel2.add(txtusername);
        txtusername.setBounds(30, 280, 280, 40);

        txtfirstname.setBackground(new java.awt.Color(0, 0, 0,0));
        txtfirstname.setText("Id Number");
        txtfirstname.setBorderColor(new java.awt.Color(230, 245, 241));
        txtfirstname.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\StudentAttend\\11185794_user_person_profile_avatar_people_icon (1).png"));
        txtfirstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfirstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfirstnameFocusLost(evt);
            }
        });
        txtfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirstnameActionPerformed(evt);
            }
        });
        txtfirstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfirstnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfirstnameKeyTyped(evt);
            }
        });
        jPanel2.add(txtfirstname);
        txtfirstname.setBounds(30, 70, 280, 40);

        txtfirstname1.setBackground(new java.awt.Color(0, 0, 0,0));
        txtfirstname1.setText("First Name");
        txtfirstname1.setBorderColor(new java.awt.Color(230, 245, 241));
        txtfirstname1.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\StudentAttend\\11185794_user_person_profile_avatar_people_icon (1).png"));
        txtfirstname1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfirstname1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfirstname1FocusLost(evt);
            }
        });
        txtfirstname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirstname1ActionPerformed(evt);
            }
        });
        txtfirstname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfirstname1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfirstname1KeyTyped(evt);
            }
        });
        jPanel2.add(txtfirstname1);
        txtfirstname1.setBounds(30, 130, 130, 40);

        txtlastname.setBackground(new java.awt.Color(0, 0, 0,0));
        txtlastname.setText("Last Name");
        txtlastname.setBorderColor(new java.awt.Color(230, 245, 241));
        txtlastname.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\StudentAttend\\11185794_user_person_profile_avatar_people_icon (1).png"));
        txtlastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtlastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtlastnameFocusLost(evt);
            }
        });
        txtlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlastnameActionPerformed(evt);
            }
        });
        txtlastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlastnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlastnameKeyTyped(evt);
            }
        });
        jPanel2.add(txtlastname);
        txtlastname.setBounds(180, 130, 130, 40);

        cbcourse.setBackground(new java.awt.Color(0,0,0,0));
        cbcourse.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbcourse.setForeground(new java.awt.Color(122, 140, 141));
        cbcourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course" }));
        jPanel2.add(cbcourse);
        cbcourse.setBounds(30, 230, 140, 40);

        cbyear.setBackground(new java.awt.Color(0,0,0,0));
        cbyear.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbyear.setForeground(new java.awt.Color(122, 140, 141));
        cbyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Year" }));
        jPanel2.add(cbyear);
        cbyear.setBounds(180, 230, 130, 40);

        cbgender.setBackground(new java.awt.Color(0,0,0,0));
        cbgender.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbgender.setForeground(new java.awt.Color(122, 140, 141));
        cbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female", "Others" }));
        cbgender.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        cbgender.setRequestFocusEnabled(false);
        jPanel2.add(cbgender);
        cbgender.setBounds(30, 180, 120, 40);

        txtconfirmpassword.setText("Confirm Password");
        txtconfirmpassword.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\StudentAttend\\8491307_padlock_security_password_icon.png"));
        txtconfirmpassword.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                txtconfirmpasswordHierarchyChanged(evt);
            }
        });
        txtconfirmpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtconfirmpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtconfirmpasswordFocusLost(evt);
            }
        });
        txtconfirmpassword.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtconfirmpasswordInputMethodTextChanged(evt);
            }
        });
        txtconfirmpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconfirmpasswordActionPerformed(evt);
            }
        });
        txtconfirmpassword.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtconfirmpasswordPropertyChange(evt);
            }
        });
        txtconfirmpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtconfirmpasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtconfirmpasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtconfirmpasswordKeyTyped(evt);
            }
        });
        jPanel2.add(txtconfirmpassword);
        txtconfirmpassword.setBounds(30, 400, 280, 40);

        btnsignin.setForeground(new java.awt.Color(255, 255, 255));
        btnsignin.setText("Sign Up");
        btnsignin.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnsignin.setRadius(50);
        btnsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsigninActionPerformed(evt);
            }
        });
        jPanel2.add(btnsignin);
        btnsignin.setBounds(50, 460, 246, 42);

        jDateChooser1.setBackground(new java.awt.Color(0,0,0,0));
        jPanel2.add(jDateChooser1);
        jDateChooser1.setBounds(160, 180, 150, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(signuppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signuppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
        dispose();
       new signin().setVisible(true);
       

    }//GEN-LAST:event_btnsignupActionPerformed

    private void showpasswordStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_showpasswordStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_showpasswordStateChanged

    private void showpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordActionPerformed
        if(showpassword.isSelected()){
            txtpassword.setEchoChar((char)0);
        }else{
            txtpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_showpasswordActionPerformed

    private void btnsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsigninActionPerformed
        dispose();
    JOptionPane.showMessageDialog(null,"SuccessFully Created Account","Successfull",JOptionPane.INFORMATION_MESSAGE);
    new signin().setVisible(true);
    }//GEN-LAST:event_btnsigninActionPerformed

    private void txtpasswordHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_txtpasswordHierarchyChanged

    }//GEN-LAST:event_txtpasswordHierarchyChanged

    private void txtpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusGained
        if(txtpassword.getText().equalsIgnoreCase("Password")){
            txtpassword.setText(null);

        }
    }//GEN-LAST:event_txtpasswordFocusGained

    private void txtpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusLost
        if(txtpassword.getText().isEmpty()){
            txtpassword.setText("Password");
            txtpassword.setEchoChar((char)0);
            showpassword.setVisible(false);
        }
    }//GEN-LAST:event_txtpasswordFocusLost

    private void txtpasswordInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtpasswordInputMethodTextChanged

    }//GEN-LAST:event_txtpasswordInputMethodTextChanged

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed

    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtpasswordPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtpasswordPropertyChange

    }//GEN-LAST:event_txtpasswordPropertyChange

    private void txtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyPressed
        txtpassword.setEchoChar('*');
        if(txtpassword.getText().equalsIgnoreCase("Password") || txtpassword.getText().isEmpty()){
            showpassword.setVisible(false);

        }else{
            showpassword.setVisible(true);

        }
    }//GEN-LAST:event_txtpasswordKeyPressed

    private void txtpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyReleased

    }//GEN-LAST:event_txtpasswordKeyReleased

    private void txtpasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyTyped

    }//GEN-LAST:event_txtpasswordKeyTyped

    private void txtusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusGained
        if(txtusername.getText().equalsIgnoreCase("Username")){
            txtusername.setText(null);
            
        }
    }//GEN-LAST:event_txtusernameFocusGained

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusLost
       if(txtusername.getText().isEmpty()){
           txtusername.setText("Username");
       }
    }//GEN-LAST:event_txtusernameFocusLost

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void txtusernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameKeyReleased

    private void txtusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameKeyTyped

    private void txtfirstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfirstnameFocusGained
        if(txtfirstname.getText().equalsIgnoreCase("Id Number")){
            txtfirstname.setText(null);
        }
    }//GEN-LAST:event_txtfirstnameFocusGained

    private void txtfirstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfirstnameFocusLost
        if(txtfirstname.getText().isEmpty()){
            txtfirstname.setText("ID Number");
        }
    }//GEN-LAST:event_txtfirstnameFocusLost

    private void txtfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstnameActionPerformed

    private void txtfirstnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfirstnameKeyReleased
        if(txtfirstname.getText().isEmpty()){
            txtfirstname.setCustomIcon2(null);
        }else{

            txtfirstname.setCustomIcon2(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\image\\22 (2).gif"));

        }
    }//GEN-LAST:event_txtfirstnameKeyReleased

    private void txtfirstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfirstnameKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c== KeyEvent.VK_DELETE)) {
            evt.consume();
        }else {
             txtfirstname.setCustomIcon2(null);
             txtfirstname.setCustomIcon2(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\image\\22 (2).gif"));

        }
    }//GEN-LAST:event_txtfirstnameKeyTyped

    private void txtfirstname1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfirstname1FocusGained
       if(txtfirstname1.getText().equalsIgnoreCase("First Name")){
        txtfirstname1.setText(null);
        }
    }//GEN-LAST:event_txtfirstname1FocusGained

    private void txtfirstname1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfirstname1FocusLost
        if(txtfirstname1.getText().isEmpty()){
            txtfirstname1.setText("First Name");
        }
    }//GEN-LAST:event_txtfirstname1FocusLost

    private void txtfirstname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstname1ActionPerformed

    private void txtfirstname1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfirstname1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstname1KeyReleased

    private void txtfirstname1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfirstname1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstname1KeyTyped

    private void txtlastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlastnameFocusGained
        if(txtlastname.getText().equalsIgnoreCase("Last Name")){
            txtlastname.setText(null);
        }
    }//GEN-LAST:event_txtlastnameFocusGained

    private void txtlastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlastnameFocusLost
        if(txtlastname.getText().isEmpty()){
            txtlastname.setText("Last Name");
        }
    }//GEN-LAST:event_txtlastnameFocusLost

    private void txtlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameActionPerformed

    private void txtlastnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlastnameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameKeyReleased

    private void txtlastnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlastnameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameKeyTyped

    private void txtconfirmpasswordHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_txtconfirmpasswordHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmpasswordHierarchyChanged

    private void txtconfirmpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtconfirmpasswordFocusGained
        if(txtconfirmpassword.getText().equalsIgnoreCase("Confirm Password")){
            txtconfirmpassword.setText(null);
        }
    }//GEN-LAST:event_txtconfirmpasswordFocusGained

    private void txtconfirmpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtconfirmpasswordFocusLost
       if(txtconfirmpassword.getText().isEmpty()){
           txtconfirmpassword.setText("Confirm Password");
              txtconfirmpassword.setEchoChar((char)0);
              showconfirmpassword.setVisible(false);

       }
    }//GEN-LAST:event_txtconfirmpasswordFocusLost

    private void txtconfirmpasswordInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtconfirmpasswordInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmpasswordInputMethodTextChanged

    private void txtconfirmpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconfirmpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmpasswordActionPerformed

    private void txtconfirmpasswordPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtconfirmpasswordPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmpasswordPropertyChange

    private void txtconfirmpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconfirmpasswordKeyPressed
         txtconfirmpassword.setEchoChar('*');
        if(txtconfirmpassword.getText().equalsIgnoreCase("Password") || txtconfirmpassword.getText().isEmpty()){
            showconfirmpassword.setVisible(false);
            return;
        }
        
            showconfirmpassword.setVisible(true);

       
    }//GEN-LAST:event_txtconfirmpasswordKeyPressed

    private void txtconfirmpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconfirmpasswordKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmpasswordKeyReleased

    private void txtconfirmpasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconfirmpasswordKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmpasswordKeyTyped

    private void showconfirmpasswordStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_showconfirmpasswordStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_showconfirmpasswordStateChanged

    private void showconfirmpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showconfirmpasswordActionPerformed
   if(showconfirmpassword.isSelected()){
            txtconfirmpassword.setEchoChar((char)0);
        }else{
            txtconfirmpassword.setEchoChar('*');
        }
   
    }//GEN-LAST:event_showconfirmpasswordActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customGUI.MyButton btnsignin;
    private customGUI.MyButton btnsignup;
    private javax.swing.JComboBox<String> cbcourse;
    private javax.swing.JComboBox<String> cbgender;
    private javax.swing.JComboBox<String> cbyear;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel labelwelcome;
    private javax.swing.JCheckBox showconfirmpassword;
    private javax.swing.JCheckBox showpassword;
    private javax.swing.JPanel signuppanel;
    private customGUI.MyPasswordField txtconfirmpassword;
    private customGUI.MyTextField txtfirstname;
    private customGUI.MyTextField txtfirstname1;
    private customGUI.MyTextField txtlastname;
    private customGUI.MyPasswordField txtpassword;
    private customGUI.MyTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
