/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UserInterface.accountsettings;

import UserInterface.CustomComponents.MyTextField;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class changeusername extends javax.swing.JDialog {
    
    
    //check if the newusername and confirm username is match
    public void checkmatchup(){
        if(txtnewusername.getText() != txtconfirmnew.getText() ){
            noti.setVisible(true);
            noti1.setVisible(true);
            return;
      }
        
          noti.setVisible(false);
          noti1.setVisible(false);
        
    } 
    
   
    
    
    
            
       public changeusername(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        noti.setVisible(false);
        noti1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerpanel = new javax.swing.JPanel();
        headerlbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        confirnbtn = new UserInterface.CustomComponents.MyButton();
        txtoldusername = new UserInterface.CustomComponents.MyTextField();
        txtnewusername = new UserInterface.CustomComponents.MyTextField();
        txtconfirmnew = new UserInterface.CustomComponents.MyTextField();
        noti = new javax.swing.JLabel();
        noti1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        headerpanel.setBackground(new java.awt.Color(39, 159, 217));

        headerlbl.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        headerlbl.setText("Change Username");

        javax.swing.GroupLayout headerpanelLayout = new javax.swing.GroupLayout(headerpanel);
        headerpanel.setLayout(headerpanelLayout);
        headerpanelLayout.setHorizontalGroup(
            headerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerlbl)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        headerpanelLayout.setVerticalGroup(
            headerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerlbl)
                .addGap(16, 16, 16))
        );

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(null);

        confirnbtn.setText("Confirm");
        confirnbtn.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        confirnbtn.setRadius(30);
        jPanel1.add(confirnbtn);
        confirnbtn.setBounds(282, 236, 64, 28);

        txtoldusername.setBackground(new java.awt.Color(0, 0, 0,0));
        txtoldusername.setText("Old Username");
        txtoldusername.setBorderColor(new java.awt.Color(230, 245, 241));
        txtoldusername.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\image\\11185794_user_person_profile_avatar_people_icon (1).png"));
        txtoldusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtoldusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtoldusernameFocusLost(evt);
            }
        });
        txtoldusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoldusernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtoldusername);
        txtoldusername.setBounds(40, 40, 250, 40);

        txtnewusername.setBackground(new java.awt.Color(0, 0, 0,0));
        txtnewusername.setText("New Username");
        txtnewusername.setBorderColor(new java.awt.Color(230, 245, 241));
        txtnewusername.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\image\\11185794_user_person_profile_avatar_people_icon (1).png"));
        txtnewusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnewusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnewusernameFocusLost(evt);
            }
        });
        txtnewusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnewusernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtnewusername);
        txtnewusername.setBounds(40, 100, 250, 40);

        txtconfirmnew.setBackground(new java.awt.Color(0, 0, 0,0));
        txtconfirmnew.setText("Confirm New Username");
        txtconfirmnew.setBorderColor(new java.awt.Color(230, 245, 241));
        txtconfirmnew.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\image\\11185794_user_person_profile_avatar_people_icon (1).png"));
        txtconfirmnew.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtconfirmnewFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtconfirmnewFocusLost(evt);
            }
        });
        txtconfirmnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconfirmnewActionPerformed(evt);
            }
        });
        jPanel1.add(txtconfirmnew);
        txtconfirmnew.setBounds(40, 160, 250, 40);

        noti.setForeground(new java.awt.Color(255, 0, 0));
        noti.setText("The username didnt match up to the new!");
        jPanel1.add(noti);
        noti.setBounds(40, 140, 250, 16);

        noti1.setForeground(new java.awt.Color(255, 0, 0));
        noti1.setText("The username didnt match up to the new!");
        jPanel1.add(noti1);
        noti1.setBounds(40, 200, 250, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtoldusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtoldusernameFocusGained
        new MyTextField().focuseGained(txtoldusername, "Old UserName");
    }//GEN-LAST:event_txtoldusernameFocusGained

    private void txtoldusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtoldusernameFocusLost
      new MyTextField().focusLost(txtoldusername, "Old Username");
    }//GEN-LAST:event_txtoldusernameFocusLost

    private void txtoldusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoldusernameActionPerformed

    }//GEN-LAST:event_txtoldusernameActionPerformed

    private void txtnewusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnewusernameFocusGained
        new MyTextField().focuseGained(txtnewusername, "New Username");
    }//GEN-LAST:event_txtnewusernameFocusGained

    private void txtnewusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnewusernameFocusLost
       new MyTextField().focusLost(txtnewusername, "New Username");
    }//GEN-LAST:event_txtnewusernameFocusLost

    private void txtnewusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnewusernameActionPerformed
    checkmatchup();
    }//GEN-LAST:event_txtnewusernameActionPerformed

    private void txtconfirmnewFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtconfirmnewFocusGained
        new MyTextField().focuseGained(txtconfirmnew, "Confirm New Username");
    }//GEN-LAST:event_txtconfirmnewFocusGained

    private void txtconfirmnewFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtconfirmnewFocusLost
      new MyTextField().focusLost(txtconfirmnew, "Confirm New Username");
    }//GEN-LAST:event_txtconfirmnewFocusLost

    private void txtconfirmnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconfirmnewActionPerformed
        checkmatchup();
    }//GEN-LAST:event_txtconfirmnewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changeusername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changeusername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changeusername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changeusername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                changeusername dialog = new changeusername(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UserInterface.CustomComponents.MyButton confirnbtn;
    private javax.swing.JLabel headerlbl;
    private javax.swing.JPanel headerpanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel noti;
    private javax.swing.JLabel noti1;
    private UserInterface.CustomComponents.MyTextField txtconfirmnew;
    private UserInterface.CustomComponents.MyTextField txtnewusername;
    private UserInterface.CustomComponents.MyTextField txtoldusername;
    // End of variables declaration//GEN-END:variables
}
