/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import login.signin;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
          txtpassword.setEchoChar((char)0);
         showpassword.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signuppanel = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        btnsignup = new customGUI.MyButton();
        labelwelcome = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        showpassword = new javax.swing.JCheckBox();
        txtpassword = new customGUI.MyPasswordField();
        txtusername = new customGUI.MyTextField();
        txtfirstname = new customGUI.MyTextField();
        txtfirstname1 = new customGUI.MyTextField();
        txtlastname = new customGUI.MyTextField();
        cbcourse = new javax.swing.JComboBox<>();
        cbyear = new javax.swing.JComboBox<>();
        cbgender = new javax.swing.JComboBox<>();
        txtpassword1 = new customGUI.MyPasswordField();
        btnsignin = new customGUI.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        signuppanel.setBackground(new java.awt.Color(0, 102, 204));
        signuppanel.setForeground(new java.awt.Color(30, 30, 30));

        label1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Already Have an Account?");

        btnsignup.setForeground(new java.awt.Color(255, 255, 255));
        btnsignup.setText("Sign In");
        btnsignup.setBorderColor(new java.awt.Color(0, 0, 0));
        btnsignup.setColor(new java.awt.Color(0, 0, 0));
        btnsignup.setColorClick(new java.awt.Color(102, 102, 102));
        btnsignup.setColorOver(new java.awt.Color(51, 51, 51));
        btnsignup.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnsignup.setRadius(50);
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });

        labelwelcome.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        labelwelcome.setForeground(new java.awt.Color(255, 255, 255));
        labelwelcome.setText("Join Us User");

        javax.swing.GroupLayout signuppanelLayout = new javax.swing.GroupLayout(signuppanel);
        signuppanel.setLayout(signuppanelLayout);
        signuppanelLayout.setHorizontalGroup(
            signuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signuppanelLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(signuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsignup, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
            .addGroup(signuppanelLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(label1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signuppanelLayout.setVerticalGroup(
            signuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signuppanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelwelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsignup, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        showpassword.setContentAreaFilled(false);
        showpassword.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\StudentAttend\\9041325_eye_fill_icon (3).png"));
        showpassword.setSelectedIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\StudentAttend\\9034884_eye_off_icon (1).png"));
        showpassword.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                showpasswordStateChanged(evt);
            }
        });
        showpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(showpassword);
        showpassword.setBounds(240, 340, 19, 20);

        txtpassword.setText("Password");
        txtpassword.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\StudentAttend\\8491307_padlock_security_password_icon.png"));
        txtpassword.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                txtpasswordHierarchyChanged(evt);
            }
        });
        txtpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpasswordFocusLost(evt);
            }
        });
        txtpassword.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtpasswordInputMethodTextChanged(evt);
            }
        });
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        txtpassword.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtpasswordPropertyChange(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpasswordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpasswordKeyTyped(evt);
            }
        });
        jPanel2.add(txtpassword);
        txtpassword.setBounds(20, 330, 250, 40);

        txtusername.setBackground(new java.awt.Color(0, 0, 0,0));
        txtusername.setText("Username");
        txtusername.setBorderColor(new java.awt.Color(230, 245, 241));
        txtusername.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\StudentAttend\\11185794_user_person_profile_avatar_people_icon (1).png"));
        txtusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameFocusLost(evt);
            }
        });
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtusernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusernameKeyTyped(evt);
            }
        });
        jPanel2.add(txtusername);
        txtusername.setBounds(20, 280, 250, 40);

        txtfirstname.setBackground(new java.awt.Color(0, 0, 0,0));
        txtfirstname.setText("Id Number");
        txtfirstname.setBorderColor(new java.awt.Color(230, 245, 241));
        txtfirstname.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\StudentAttend\\11185794_user_person_profile_avatar_people_icon (1).png"));
        txtfirstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfirstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfirstnameFocusLost(evt);
            }
        });
        txtfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirstnameActionPerformed(evt);
            }
        });
        txtfirstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfirstnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfirstnameKeyTyped(evt);
            }
        });
        jPanel2.add(txtfirstname);
        txtfirstname.setBounds(20, 80, 250, 40);

        txtfirstname1.setBackground(new java.awt.Color(0, 0, 0,0));
        txtfirstname1.setText("First Name");
        txtfirstname1.setBorderColor(new java.awt.Color(230, 245, 241));
        txtfirstname1.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\StudentAttend\\11185794_user_person_profile_avatar_people_icon (1).png"));
        txtfirstname1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfirstname1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfirstname1FocusLost(evt);
            }
        });
        txtfirstname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirstname1ActionPerformed(evt);
            }
        });
        txtfirstname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfirstname1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfirstname1KeyTyped(evt);
            }
        });
        jPanel2.add(txtfirstname1);
        txtfirstname1.setBounds(20, 130, 120, 40);

        txtlastname.setBackground(new java.awt.Color(0, 0, 0,0));
        txtlastname.setText("Last Name");
        txtlastname.setBorderColor(new java.awt.Color(230, 245, 241));
        txtlastname.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\StudentAttend\\11185794_user_person_profile_avatar_people_icon (1).png"));
        txtlastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtlastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtlastnameFocusLost(evt);
            }
        });
        txtlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlastnameActionPerformed(evt);
            }
        });
        txtlastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlastnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlastnameKeyTyped(evt);
            }
        });
        jPanel2.add(txtlastname);
        txtlastname.setBounds(150, 130, 120, 40);

        cbcourse.setForeground(new java.awt.Color(122, 140, 141));
        cbcourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course" }));
        jPanel2.add(cbcourse);
        cbcourse.setBounds(20, 230, 120, 40);

        cbyear.setForeground(new java.awt.Color(122, 140, 141));
        cbyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Year" }));
        jPanel2.add(cbyear);
        cbyear.setBounds(150, 230, 120, 40);

        cbgender.setForeground(new java.awt.Color(122, 140, 141));
        cbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female", "Others" }));
        jPanel2.add(cbgender);
        cbgender.setBounds(20, 180, 110, 40);

        txtpassword1.setText("Password");
        txtpassword1.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\StudentAttend\\8491307_padlock_security_password_icon.png"));
        txtpassword1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                txtpassword1HierarchyChanged(evt);
            }
        });
        txtpassword1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpassword1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpassword1FocusLost(evt);
            }
        });
        txtpassword1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtpassword1InputMethodTextChanged(evt);
            }
        });
        txtpassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassword1ActionPerformed(evt);
            }
        });
        txtpassword1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtpassword1PropertyChange(evt);
            }
        });
        txtpassword1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpassword1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpassword1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpassword1KeyTyped(evt);
            }
        });
        jPanel2.add(txtpassword1);
        txtpassword1.setBounds(20, 380, 250, 40);

        btnsignin.setForeground(new java.awt.Color(255, 255, 255));
        btnsignin.setText("Sign Up");
        btnsignin.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnsignin.setRadius(50);
        btnsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsigninActionPerformed(evt);
            }
        });
        jPanel2.add(btnsignin);
        btnsignin.setBounds(20, 430, 246, 42);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(signuppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signuppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
        dispose();
       new signin().setVisible(true);
       

    }//GEN-LAST:event_btnsignupActionPerformed

    private void showpasswordStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_showpasswordStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_showpasswordStateChanged

    private void showpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordActionPerformed
        if(showpassword.isSelected()){
            txtpassword.setEchoChar((char)0);
        }else{
            txtpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_showpasswordActionPerformed

    private void btnsigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsigninActionPerformed
        dispose();
    JOptionPane.showMessageDialog(null,"SuccessFully Created Account","Successfull",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnsigninActionPerformed

    private void txtpasswordHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_txtpasswordHierarchyChanged

    }//GEN-LAST:event_txtpasswordHierarchyChanged

    private void txtpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusGained
        if(txtpassword.getText().equalsIgnoreCase("Password")){
            txtpassword.setText(null);

        }
    }//GEN-LAST:event_txtpasswordFocusGained

    private void txtpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusLost
        if(txtpassword.getText().isEmpty()){
            txtpassword.setText("Password");
            txtpassword.setEchoChar((char)0);

        }
    }//GEN-LAST:event_txtpasswordFocusLost

    private void txtpasswordInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtpasswordInputMethodTextChanged

    }//GEN-LAST:event_txtpasswordInputMethodTextChanged

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed

    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtpasswordPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtpasswordPropertyChange

    }//GEN-LAST:event_txtpasswordPropertyChange

    private void txtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyPressed
        txtpassword.setEchoChar('*');
        if(txtpassword.getText().equalsIgnoreCase("Password") || txtpassword.getText().isEmpty()){
            showpassword.setVisible(false);

        }else{
            showpassword.setVisible(true);

        }
    }//GEN-LAST:event_txtpasswordKeyPressed

    private void txtpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyReleased

    }//GEN-LAST:event_txtpasswordKeyReleased

    private void txtpasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyTyped

    }//GEN-LAST:event_txtpasswordKeyTyped

    private void txtusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusGained
        if(txtusername.getText().equalsIgnoreCase("Username")){
            txtusername.setText(null);
            
        }
    }//GEN-LAST:event_txtusernameFocusGained

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusLost
       if(txtusername.getText().isEmpty()){
           txtusername.setText("Username");
       }
    }//GEN-LAST:event_txtusernameFocusLost

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void txtusernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameKeyReleased

    private void txtusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameKeyTyped

    private void txtfirstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfirstnameFocusGained
        if(txtfirstname.getText().equalsIgnoreCase("First Name")){
            txtfirstname.setText(null);
        }
    }//GEN-LAST:event_txtfirstnameFocusGained

    private void txtfirstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfirstnameFocusLost
        if(txtfirstname.getText().isEmpty()){
            txtfirstname.setText("First Name");
        }
    }//GEN-LAST:event_txtfirstnameFocusLost

    private void txtfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstnameActionPerformed

    private void txtfirstnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfirstnameKeyReleased
        if(txtfirstname.getText().isEmpty()){
            txtfirstname.setCustomIcon2(null);
        }else{

            txtfirstname.setCustomIcon2(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\StudentAttend\\22 (2).gif"));

        }
    }//GEN-LAST:event_txtfirstnameKeyReleased

    private void txtfirstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfirstnameKeyTyped
        if(evt.getSource() == txtfirstname){
            txtfirstname.setCustomIcon2(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\StudentAttend\\22 (2).gif"));
        }else{
            txtfirstname.setCustomIcon2(null);

        }
    }//GEN-LAST:event_txtfirstnameKeyTyped

    private void txtfirstname1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfirstname1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstname1FocusGained

    private void txtfirstname1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfirstname1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstname1FocusLost

    private void txtfirstname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstname1ActionPerformed

    private void txtfirstname1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfirstname1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstname1KeyReleased

    private void txtfirstname1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfirstname1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstname1KeyTyped

    private void txtlastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlastnameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameFocusGained

    private void txtlastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlastnameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameFocusLost

    private void txtlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameActionPerformed

    private void txtlastnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlastnameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameKeyReleased

    private void txtlastnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlastnameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameKeyTyped

    private void txtpassword1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_txtpassword1HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassword1HierarchyChanged

    private void txtpassword1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassword1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassword1FocusGained

    private void txtpassword1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassword1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassword1FocusLost

    private void txtpassword1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtpassword1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassword1InputMethodTextChanged

    private void txtpassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassword1ActionPerformed

    private void txtpassword1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtpassword1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassword1PropertyChange

    private void txtpassword1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassword1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassword1KeyPressed

    private void txtpassword1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassword1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassword1KeyReleased

    private void txtpassword1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassword1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassword1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customGUI.MyButton btnsignin;
    private customGUI.MyButton btnsignup;
    private javax.swing.JComboBox<String> cbcourse;
    private javax.swing.JComboBox<String> cbgender;
    private javax.swing.JComboBox<String> cbyear;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel labelwelcome;
    private javax.swing.JCheckBox showpassword;
    private javax.swing.JPanel signuppanel;
    private customGUI.MyTextField txtfirstname;
    private customGUI.MyTextField txtfirstname1;
    private customGUI.MyTextField txtlastname;
    private customGUI.MyPasswordField txtpassword;
    private customGUI.MyPasswordField txtpassword1;
    private customGUI.MyTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
