/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package accountsetting;

import accountsetting.changepersonalinfo;



/**
 *
 * @author Admin
 */
public class accountsettings extends javax.swing.JDialog {
 
   
    public accountsettings(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        btnchangeuser = new customGUI.MyButton();
        btnchangepassword = new customGUI.MyButton();
        myButton4 = new customGUI.MyButton();
        btnchangepersonal = new customGUI.MyButton();
        lblyearholder1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbldispay = new javax.swing.JLabel();
        lbldisplay2 = new javax.swing.JLabel();
        lblidholder = new javax.swing.JLabel();
        lblnameholder = new javax.swing.JLabel();
        lbldisplay4 = new javax.swing.JLabel();
        lbldisplay5 = new javax.swing.JLabel();
        lbldisplay6 = new javax.swing.JLabel();
        lbldisplay7 = new javax.swing.JLabel();
        lblbirthdateholder = new javax.swing.JLabel();
        lbldepartmentholder = new javax.swing.JLabel();
        lblyearholder = new javax.swing.JLabel();
        lblgenderholder = new javax.swing.JLabel();
        profilepicture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(39, 159, 217));

        btnchangeuser.setBackground(new java.awt.Color(39, 159, 217));
        btnchangeuser.setText("Change UserName");
        btnchangeuser.setBorderColor(new java.awt.Color(39, 159, 217));
        btnchangeuser.setColor(new java.awt.Color(39, 159, 217));
        btnchangeuser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnchangeuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangeuserActionPerformed(evt);
            }
        });

        btnchangepassword.setBackground(new java.awt.Color(39, 159, 217));
        btnchangepassword.setText("Change Password");
        btnchangepassword.setBorderColor(new java.awt.Color(39, 159, 217));
        btnchangepassword.setColor(new java.awt.Color(39, 159, 217));
        btnchangepassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnchangepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangepasswordActionPerformed(evt);
            }
        });

        myButton4.setBackground(new java.awt.Color(39, 159, 217));
        myButton4.setText("Login/Logout History");
        myButton4.setBorderColor(new java.awt.Color(39, 159, 217));
        myButton4.setColor(new java.awt.Color(39, 159, 217));
        myButton4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnchangepersonal.setBackground(new java.awt.Color(39, 159, 217));
        btnchangepersonal.setText("Change Personal Info");
        btnchangepersonal.setBorderColor(new java.awt.Color(39, 159, 217));
        btnchangepersonal.setColor(new java.awt.Color(39, 159, 217));
        btnchangepersonal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnchangepersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangepersonalActionPerformed(evt);
            }
        });

        lblyearholder1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblyearholder1.setForeground(new java.awt.Color(0, 0, 0));
        lblyearholder1.setText("Account Settings");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnchangeuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(myButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblyearholder1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnchangepersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnchangepassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblyearholder1)
                .addGap(31, 31, 31)
                .addComponent(btnchangepersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnchangeuser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnchangepassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lbldispay.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbldispay.setForeground(new java.awt.Color(0, 0, 0));
        lbldispay.setText("ID:");

        lbldisplay2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbldisplay2.setForeground(new java.awt.Color(0, 0, 0));
        lbldisplay2.setText("Name:");

        lblidholder.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblidholder.setForeground(new java.awt.Color(0, 0, 0));
        lblidholder.setText("IDNUMBER");

        lblnameholder.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblnameholder.setForeground(new java.awt.Color(0, 0, 0));
        lblnameholder.setText("FIRST NAME");

        lbldisplay4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbldisplay4.setForeground(new java.awt.Color(0, 0, 0));
        lbldisplay4.setText("Birthdate:");

        lbldisplay5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbldisplay5.setForeground(new java.awt.Color(0, 0, 0));
        lbldisplay5.setText("Department:");

        lbldisplay6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbldisplay6.setForeground(new java.awt.Color(0, 0, 0));
        lbldisplay6.setText("YearLevel:");

        lbldisplay7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbldisplay7.setForeground(new java.awt.Color(0, 0, 0));
        lbldisplay7.setText("Gender:");

        lblbirthdateholder.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblbirthdateholder.setForeground(new java.awt.Color(0, 0, 0));
        lblbirthdateholder.setText("BirthDate");

        lbldepartmentholder.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbldepartmentholder.setForeground(new java.awt.Color(0, 0, 0));
        lbldepartmentholder.setText("Department");

        lblyearholder.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblyearholder.setForeground(new java.awt.Color(0, 0, 0));
        lblyearholder.setText("Year");

        lblgenderholder.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblgenderholder.setForeground(new java.awt.Color(0, 0, 0));
        lblgenderholder.setText("Gender");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(profilepicture, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbldispay, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblidholder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(179, 179, 179))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbldisplay2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblnameholder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(159, 159, 159))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbldisplay4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblbirthdateholder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbldisplay7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblgenderholder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(85, 85, 85))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbldisplay5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbldepartmentholder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbldisplay6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblyearholder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(69, 69, 69)))
                .addGap(247, 247, 247))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbldispay)
                            .addComponent(lblidholder))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbldisplay2)
                            .addComponent(lblnameholder)))
                    .addComponent(profilepicture, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldisplay7)
                    .addComponent(lblgenderholder))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldisplay4)
                    .addComponent(lblbirthdateholder))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldisplay5)
                    .addComponent(lbldepartmentholder))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldisplay6)
                    .addComponent(lblyearholder))
                .addGap(0, 225, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    
    }//GEN-LAST:event_formWindowClosed

    private void btnchangepersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangepersonalActionPerformed
        new changepersonalinfo(null,true).setVisible(true);
    }//GEN-LAST:event_btnchangepersonalActionPerformed

    private void btnchangeuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangeuserActionPerformed
      new changeusername(null,true).setVisible(true);
    }//GEN-LAST:event_btnchangeuserActionPerformed

    private void btnchangepasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangepasswordActionPerformed
        new changepassword(null,true,lblidholder.getText()).setVisible(true);

    }//GEN-LAST:event_btnchangepasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accountsettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accountsettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accountsettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accountsettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                accountsettings dialog = new accountsettings(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customGUI.MyButton btnchangepassword;
    private customGUI.MyButton btnchangepersonal;
    private customGUI.MyButton btnchangeuser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    public javax.swing.JLabel lblbirthdateholder;
    public javax.swing.JLabel lbldepartmentholder;
    private javax.swing.JLabel lbldispay;
    private javax.swing.JLabel lbldisplay2;
    private javax.swing.JLabel lbldisplay4;
    private javax.swing.JLabel lbldisplay5;
    private javax.swing.JLabel lbldisplay6;
    private javax.swing.JLabel lbldisplay7;
    public javax.swing.JLabel lblgenderholder;
    public javax.swing.JLabel lblidholder;
    public javax.swing.JLabel lblnameholder;
    public javax.swing.JLabel lblyearholder;
    private javax.swing.JLabel lblyearholder1;
    private customGUI.MyButton myButton4;
    public javax.swing.JLabel profilepicture;
    // End of variables declaration//GEN-END:variables
}
