/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package accountsetting;

/**
 *
 * @author Admin
 */
public class changeusername extends javax.swing.JDialog {
    
    public void checkmatchup(){
        if(txtnewusername.getText() != txtconfirmnew.getText() ){
          confirnbtn.setEnabled(false);
            noti.setVisible(true);
      }else{
          confirnbtn.setEnabled(true);
          noti.setVisible(false);
        } 
    } 
    
    
    
    
            
       public changeusername(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        noti.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerpanel = new javax.swing.JPanel();
        headerlbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        confirnbtn = new customGUI.MyButton();
        txtoldusername = new customGUI.MyTextField();
        txtnewusername = new customGUI.MyTextField();
        txtconfirmnew = new customGUI.MyTextField();
        noti = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        headerpanel.setBackground(new java.awt.Color(39, 159, 217));

        headerlbl.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        headerlbl.setText("Change Username");

        javax.swing.GroupLayout headerpanelLayout = new javax.swing.GroupLayout(headerpanel);
        headerpanel.setLayout(headerpanelLayout);
        headerpanelLayout.setHorizontalGroup(
            headerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerlbl)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        headerpanelLayout.setVerticalGroup(
            headerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerlbl)
                .addGap(16, 16, 16))
        );

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(null);

        confirnbtn.setText("Confirm");
        confirnbtn.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        confirnbtn.setRadius(30);
        jPanel1.add(confirnbtn);
        confirnbtn.setBounds(282, 236, 64, 28);

        txtoldusername.setBackground(new java.awt.Color(0, 0, 0,0));
        txtoldusername.setText("Old Username");
        txtoldusername.setBorderColor(new java.awt.Color(230, 245, 241));
        txtoldusername.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\image\\11185794_user_person_profile_avatar_people_icon (1).png"));
        txtoldusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtoldusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtoldusernameFocusLost(evt);
            }
        });
        txtoldusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoldusernameActionPerformed(evt);
            }
        });
        txtoldusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtoldusernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtoldusernameKeyTyped(evt);
            }
        });
        jPanel1.add(txtoldusername);
        txtoldusername.setBounds(40, 40, 250, 40);

        txtnewusername.setBackground(new java.awt.Color(0, 0, 0,0));
        txtnewusername.setText("New Username");
        txtnewusername.setBorderColor(new java.awt.Color(230, 245, 241));
        txtnewusername.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\image\\11185794_user_person_profile_avatar_people_icon (1).png"));
        txtnewusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnewusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnewusernameFocusLost(evt);
            }
        });
        txtnewusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnewusernameActionPerformed(evt);
            }
        });
        txtnewusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnewusernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnewusernameKeyTyped(evt);
            }
        });
        jPanel1.add(txtnewusername);
        txtnewusername.setBounds(40, 100, 250, 40);

        txtconfirmnew.setBackground(new java.awt.Color(0, 0, 0,0));
        txtconfirmnew.setText("Confirm New Username");
        txtconfirmnew.setBorderColor(new java.awt.Color(230, 245, 241));
        txtconfirmnew.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\image\\11185794_user_person_profile_avatar_people_icon (1).png"));
        txtconfirmnew.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtconfirmnewFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtconfirmnewFocusLost(evt);
            }
        });
        txtconfirmnew.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtconfirmnewInputMethodTextChanged(evt);
            }
        });
        txtconfirmnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconfirmnewActionPerformed(evt);
            }
        });
        txtconfirmnew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtconfirmnewKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtconfirmnewKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtconfirmnewKeyTyped(evt);
            }
        });
        jPanel1.add(txtconfirmnew);
        txtconfirmnew.setBounds(40, 160, 250, 40);

        noti.setForeground(new java.awt.Color(255, 0, 0));
        noti.setText("The username didnt match up to the new!");
        jPanel1.add(noti);
        noti.setBounds(40, 200, 250, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtoldusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtoldusernameFocusGained
        if(txtoldusername.getText().equalsIgnoreCase("Old Username")){
            txtoldusername.setText(null);
        }
    }//GEN-LAST:event_txtoldusernameFocusGained

    private void txtoldusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtoldusernameFocusLost
        if(txtoldusername.getText().isEmpty()){
            txtoldusername.setText("Old Username");
        }
    }//GEN-LAST:event_txtoldusernameFocusLost

    private void txtoldusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoldusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoldusernameActionPerformed

    private void txtoldusernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtoldusernameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoldusernameKeyReleased

    private void txtoldusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtoldusernameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoldusernameKeyTyped

    private void txtnewusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnewusernameFocusGained
        if(txtnewusername.getText().equalsIgnoreCase("New Username")){
            txtnewusername.setText(null);
        }
    }//GEN-LAST:event_txtnewusernameFocusGained

    private void txtnewusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnewusernameFocusLost
        if(txtnewusername.getText().isEmpty()){
            txtnewusername.setText("New Username");
        }
    }//GEN-LAST:event_txtnewusernameFocusLost

    private void txtnewusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnewusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnewusernameActionPerformed

    private void txtnewusernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnewusernameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnewusernameKeyReleased

    private void txtnewusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnewusernameKeyTyped
      
    }//GEN-LAST:event_txtnewusernameKeyTyped

    private void txtconfirmnewFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtconfirmnewFocusGained
        if(txtconfirmnew.getText().equalsIgnoreCase("Confirm New Username")){
            txtconfirmnew.setText(null);
        }
       
    }//GEN-LAST:event_txtconfirmnewFocusGained

    private void txtconfirmnewFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtconfirmnewFocusLost
       if(txtconfirmnew.getText().isEmpty()){
           txtconfirmnew.setText("Confirm New Username");
       }
    }//GEN-LAST:event_txtconfirmnewFocusLost

    private void txtconfirmnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconfirmnewActionPerformed
        checkmatchup();
    }//GEN-LAST:event_txtconfirmnewActionPerformed

    private void txtconfirmnewKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconfirmnewKeyReleased
       
    }//GEN-LAST:event_txtconfirmnewKeyReleased

    private void txtconfirmnewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconfirmnewKeyTyped
   
    }//GEN-LAST:event_txtconfirmnewKeyTyped

    private void txtconfirmnewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconfirmnewKeyPressed
        
    }//GEN-LAST:event_txtconfirmnewKeyPressed

    private void txtconfirmnewInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtconfirmnewInputMethodTextChanged
         
    }//GEN-LAST:event_txtconfirmnewInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changeusername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changeusername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changeusername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changeusername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                changeusername dialog = new changeusername(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customGUI.MyButton confirnbtn;
    private javax.swing.JLabel headerlbl;
    private javax.swing.JPanel headerpanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel noti;
    private customGUI.MyTextField txtconfirmnew;
    private customGUI.MyTextField txtnewusername;
    private customGUI.MyTextField txtoldusername;
    // End of variables declaration//GEN-END:variables
}
