/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admin;

import customGUI.MyTextField;

/**
 *
 * @author Admin
 */
public class Events extends javax.swing.JPanel {

    /**
     * Creates new form dashboard
     */
    public Events() {
        initComponents();
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txteventname = new customGUI.MyTextField();
        lbldesign1 = new javax.swing.JLabel();
        lbldesignyear1 = new javax.swing.JLabel();
        lbldesignyear2 = new javax.swing.JLabel();
        lbldesignyear3 = new javax.swing.JLabel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        timePicker1 = new com.github.lgooddatepicker.components.TimePicker();
        timePicker2 = new com.github.lgooddatepicker.components.TimePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        myTable2 = new customGUI.MyTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        myTable3 = new customGUI.MyTable();
        txtsearch = new customGUI.MyTextField();
        btnsearch1 = new customGUI.MyButton();

        setBackground(new java.awt.Color(181, 181, 181));

        jPanel3.setBackground(new java.awt.Color(181, 181, 181));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(null);

        txteventname.setText("Event Name");
        txteventname.setBackground(new java.awt.Color(0, 0, 0,0));
        txteventname.setBorderColor(new java.awt.Color(230, 245, 241));
        txteventname.setCustomIcon1(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\image\\11185794_user_person_profile_avatar_people_icon (1).png"));
        txteventname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txteventnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txteventnameFocusLost(evt);
            }
        });
        jPanel2.add(txteventname);
        txteventname.setBounds(10, 20, 320, 40);

        lbldesign1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbldesign1.setForeground(java.awt.Color.black);
        lbldesign1.setText("Event Name:");
        jPanel2.add(lbldesign1);
        lbldesign1.setBounds(10, 0, 80, 16);

        lbldesignyear1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbldesignyear1.setForeground(java.awt.Color.black);
        lbldesignyear1.setText("Date");
        jPanel2.add(lbldesignyear1);
        lbldesignyear1.setBounds(10, 60, 40, 16);

        lbldesignyear2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbldesignyear2.setForeground(java.awt.Color.black);
        lbldesignyear2.setText("Time in");
        jPanel2.add(lbldesignyear2);
        lbldesignyear2.setBounds(370, 0, 90, 16);

        lbldesignyear3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbldesignyear3.setForeground(java.awt.Color.black);
        lbldesignyear3.setText("Time Out");
        jPanel2.add(lbldesignyear3);
        lbldesignyear3.setBounds(610, 0, 90, 16);
        jPanel2.add(datePicker1);
        datePicker1.setBounds(10, 80, 320, 40);
        jPanel2.add(timePicker1);
        timePicker1.setBounds(590, 20, 140, 40);
        jPanel2.add(timePicker2);
        timePicker2.setBounds(360, 20, 150, 40);

        myTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Student Id", "Name", "Department", "Year"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(myTable2);
        if (myTable2.getColumnModel().getColumnCount() > 0) {
            myTable2.getColumnModel().getColumn(0).setHeaderValue("Id");
            myTable2.getColumnModel().getColumn(1).setHeaderValue("Student Id");
            myTable2.getColumnModel().getColumn(4).setHeaderValue("Year");
        }

        myTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Event", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(myTable3);

        txtsearch.setText("Search");
        txtsearch.setBackground(java.awt.Color.white);
        txtsearch.setBorderColor(new java.awt.Color(181, 181, 181));
        txtsearch.setCustomIcon2(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\image\\3741750_bussiness_ecommerce_marketplace_onlinestore_search_icon (1).png"));
        txtsearch.setRadius(30);
        txtsearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsearchFocusLost(evt);
            }
        });

        btnsearch1.setText("Search");
        btnsearch1.setRadius(30);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtsearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)))
                        .addGap(48, 48, 48)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1106, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txteventnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txteventnameFocusGained
       new MyTextField().focuseGained(txteventname, "Event Name");
    }//GEN-LAST:event_txteventnameFocusGained

    private void txteventnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txteventnameFocusLost
        new MyTextField().focusLost(txteventname, "Event Name");
    }//GEN-LAST:event_txteventnameFocusLost

    private void txtsearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsearchFocusGained
        new MyTextField().focuseGained(txtsearch,"Search");
    }//GEN-LAST:event_txtsearchFocusGained

    private void txtsearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsearchFocusLost
        new MyTextField().focusLost(txtsearch,"Search");
    }//GEN-LAST:event_txtsearchFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customGUI.MyButton btnsearch1;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbldesign1;
    private javax.swing.JLabel lbldesignyear1;
    private javax.swing.JLabel lbldesignyear2;
    private javax.swing.JLabel lbldesignyear3;
    private customGUI.MyTable myTable2;
    private customGUI.MyTable myTable3;
    private com.github.lgooddatepicker.components.TimePicker timePicker1;
    private com.github.lgooddatepicker.components.TimePicker timePicker2;
    private customGUI.MyTextField txteventname;
    private customGUI.MyTextField txtsearch;
    // End of variables declaration//GEN-END:variables
  
}
